[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license-file = "LICENSE"
repository = "https://github.com/skys3/skys3"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
bytes = "1.12.1"
rand = "0.9.5"
skys3-io = { path = "crates/skys3-io" }
tempfile = { version = "3.27.0", default-features = false }
tokio = "1.53.1"
turmoil = "0.7.2"
